version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jalvaro
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my-store
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
